import Head from "next/head";

import Header from "../components/header/Header";
import Body from "../components/body/Body";
import Main from "../components/main/Main";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Body>
        <Header>Header section</Header>
        <Main>
          Main section with Lorem ipsum dolor sit amet, consectetur adipiscing
          elit, sed do eiusmod tempor incididunt ut labore et dolore magna
          aliqua. Amet risus nullam eget felis eget nunc. Vitae suscipit tellus
          mauris a diam maecenas sed enim. Auctor eu augue ut lectus arcu
          bibendum at varius vel. Cras sed felis eget velit aliquet sagittis id.
          Amet dictum sit amet justo donec. Sem et tortor consequat id porta.
          Dictum varius duis at consectetur lorem donec massa. Auctor augue
          mauris augue neque gravida in. Amet cursus sit amet dictum. Vestibulum
          lorem sed risus ultricies tristique nulla aliquet enim. Adipiscing
          commodo elit at imperdiet dui accumsan sit. Adipiscing vitae proin
          sagittis nisl rhoncus mattis rhoncus. In dictum non consectetur a erat
          nam at. Nulla facilisi etiam dignissim diam quis enim lobortis
          scelerisque. Quam lacus suspendisse faucibus interdum posuere lorem
          ipsum dolor. Ornare lectus sit amet est placerat in egestas. Senectus
          et netus et malesuada fames ac turpis. Tristique sollicitudin nibh
          sitget. Aliquam purus sit amet luctus venenatis lectus magna
          fringilla. Risus feugiat in ante metus dictum at tempor commodo
          ullamcorper. Nec ultrices dui sapien eget mi proin sed libero enim.
          Pellentesque sit amet porttitor eget dolor morbi non. Dolor morbi non
          arcu risus quis. Massa vitae tortor condimentum lacinia quis. Felis
          imperdiet proin fermentum leo. Feugiat scelerisque varius morbi enim
          nunc. Posuere sollicitudin aliquam ultrices sagittis orci a
          scelerisque purus semper. Donec adipiscing tristique risus nec feugiat
          in fermentum posuere. Feugiat scelerisque varius morbi enim nunc
          faucibus. Mattis nunc sed blandit libero
        </Main>
        <Footer>Footer section</Footer>
      </Body>
    </>
  );
}
